# Camunda Configurations
spring:
   datasource:
     platform: mysql
     driverClassName: com.mysql.jdbc.Driver
     url: ${CAMUNDA_PE_DATASOURCE_URL}
     username: ${CAMUNDA_PE_DATASOURCE_USERNAME}
     password: ${CAMUNDA_PE_DATASOURCE_PASSWORD}
   jpa:
     database: default
     properties.hibernate.format_sql: true
     hibernate.ddl-auto: update
     generate-ddl: true
     show-sql: true    
spring.main.allow-bean-definition-overriding: true

# spring.datasource:
#   url: jdbc:h2:./camunda-db;DB_CLOSE_DELAY=-1;MVCC=TRUE;DB_CLOSE_ON_EXIT=FALSE
#   username: sa
#   password: sa
# spring.h2.console.enabled: true

spring.jersey.application-path: cc-api
spring.application.name: creditcard-app


camunda.bpm:
  history-level: full
  default-serialization-format: application/json
  auto-deployment-enabled: true
  admin-user:
    id: admin
    password: Camunda@2020
    firstName: EAS
    lastName: IPM
  filter:
    create: All Tasks
server.port: ${CC_PROCESS_APP_PORT}

# App Configurations
st.cc:
   timeout.duration: "PT30M"
   address.validation.url: https://www.yaddress.net/api/Address   
   creditscore.validation.url: ${CS_PROCESS_APP_URL}/credit-score
 

      
