/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.9).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.cognizant.eas.ipm.camunda.creditscore.proxy.api;

import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import io.swagger.annotations.*;
import com.cognizant.eas.ipm.camunda.creditscore.proxy.model.CreditScoreRequest;
import com.cognizant.eas.ipm.camunda.creditscore.proxy.model.CreditScoreResponse;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "com.cognizant.eas.ipm.camunda.creditscore.proxy.codegen.languages.SpringCodegen", date = "2019-11-24T03:50:21.291Z")

@Api(value = "credit-score", description = "the credit-score API")
public interface CreditScoreApi {

    @ApiOperation(value = "Get credit Score", nickname = "getCreditScore", notes = "", response = CreditScoreResponse.class, responseContainer = "List", tags={ "Credit Score", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation", response = CreditScoreResponse.class, responseContainer = "List") })
    @RequestMapping(value = "/credit-score",
        produces = { "application/json", "application/xml" }, 
        consumes = { "application/json", "application/xml" },
        method = RequestMethod.POST)
    ResponseEntity<CreditScoreResponse> getCreditScore(@ApiParam(value = "Credit Score Request" ,required=true )  @Valid @RequestBody CreditScoreRequest body);

}
